<a href="https://colab.research.google.com/github/alvquiJuan/numpy-talk/blob/master/getting_started_with_numpy_(part_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
my_array=np.linspace(0,10,23)
print(my_array)


[ 0.          0.45454545  0.90909091  1.36363636  1.81818182  2.27272727
  2.72727273  3.18181818  3.63636364  4.09090909  4.54545455  5.
  5.45454545  5.90909091  6.36363636  6.81818182  7.27272727  7.72727273
  8.18181818  8.63636364  9.09090909  9.54545455 10.        ]


In [0]:
fith_element=my_array[4]
print(fith_element)

1.8181818181818181


In [0]:
after_fith=my_array[4:]
print(after_fith)

[ 1.81818182  2.27272727  2.72727273  3.18181818  3.63636364  4.09090909
  4.54545455  5.          5.45454545  5.90909091  6.36363636  6.81818182
  7.27272727  7.72727273  8.18181818  8.63636364  9.09090909  9.54545455
 10.        ]


In [0]:
before_fith=my_array[:4]
print(before_fith)

[0.         0.45454545 0.90909091 1.36363636]


In [0]:
fith_last=my_array[-4]
print(fith_last)

8.636363636363637


In [0]:
intermediate=my_array[4:-4]
print(intermediate)

[1.81818182 2.27272727 2.72727273 3.18181818 3.63636364 4.09090909
 4.54545455 5.         5.45454545 5.90909091 6.36363636 6.81818182
 7.27272727 7.72727273 8.18181818]


In [0]:
np.random.seed(42)
a=np.random.rand(9)
b=np.random.rand(9)
print(a)
print(b)
c=a+b
print(c)
d=a-b
print(d)
m=a.reshape(3,3)
print(m)


[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501]
[0.70807258 0.02058449 0.96990985 0.83244264 0.21233911 0.18182497
 0.18340451 0.30424224 0.52475643]
[1.0826127  0.9712988  1.70190379 1.43110112 0.36835775 0.33781949
 0.24148812 1.17041839 1.12587144]
[-0.33353246  0.93012981 -0.23791591 -0.23378416 -0.05632047 -0.02583045
 -0.1253209   0.5619339   0.07635858]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
